### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GameIterator'

### ISSUE THREAD

**Issue by FF27** [ashudeep/ConvChess#1]
i've just putted the **sample.pgn** inside a /ConvChess/src/generate_data/pgn directory.
when starting` python get_train_data_large.py   --dir /ConvChess/src/generate_data/ --odir /ConvChess/src/generate_data/pgn/` it gives me this output : 

```
sample.pgn file opened....
Traceback (most recent call last):
  File "get_train_data_large.py", line 98, in <module>
    for game in pgn.GameIterator(PGN_DATA_DIR+"/"+f):
AttributeError: 'module' object has no attribute 'GameIterator'

```
seems that the problem is in line 98 

`for game in pgn.GameIterator(PGN_DATA_DIR+"/"+f):`

but pgnparser sintax seems correct

any idea?

**Comment by ashudeep** [comment]
Try installing pgnparser from here: https://github.com/renatopp/pgnparser
Just clone and do python setup.py install

**Comment by FF27** [comment]
```
python test_pngparser.py 
..........
----------------------------------------------------------------------
Ran 10 tests in 0.002s

OK
```

done it by git after installing from sources, still the same output..

**Comment by ashudeep** [comment]
Did you first install it from pip or elsewhere. In that case, you might need to remove that first. Then install from this repo. In any case you can check which pgnparser is being imported when you do import pgnparser. I can get back to you when I get a chance to try it out in my local repo.

**Comment by FF27** [comment]
No, totally removed with pip and then re-installed with  python setup.py install

now works

thanks!
